### ISSUE TITLE
语法的处理还有一层 DSL？

### ISSUE THREAD

**Issue by lfkdsk** [bajdcc/jMiniLang#1]
可以试试直接写成 BNF 的表达模式？

**Comment by bajdcc** [comment]
程序用**LR分析**来解析我自定义的jMiniLang语言，既然从C++移植过来，这些重载就不顶用了，所以我将DSL用**字符串**来表示，所以还要用一层Syntax类解析DSL，BNF范式在LALR1.grammar中的[Grammar.java](https://github.com/bajdcc/jMiniLang/blob/master/src/priv/bajdcc/LALR1/grammar/Grammar.java)中。
既然DSL是字符串，有着仿DSL的语法所以还得解析DSL，这个我用LL分析去做了，在[Syntax.java](https://github.com/bajdcc/jMiniLang/blob/master/src/priv/bajdcc/LALR1/syntax/Syntax.java)中。

**Comment by lfkdsk** [comment]
嗯，明白你的意思啦，我之前说的是试试 Parser Combinators去描述语法。
